from database import get_connection
from tabulate import tabulate

from reportlab.lib import colors
from reportlab.lib.styles import getSampleStyleSheet
from reportlab.lib.pagesizes import letter
from reportlab.platypus import (
    SimpleDocTemplate,
    Table,
    TableStyle,
    Paragraph,
    Spacer
)
from datetime import datetime



# -------------------- TABLE HEADERS --------------------

SUPPLIER_HEADERS = [
    "Supplier ID",
    "Supplier Name",
    "Contact Person",
    "Phone",
    "Email",
    "Address"
]

PRODUCT_HEADERS = [
    "Product ID",
    "Product Name",
    "Category",
    "Brand",
    "Selling Price",
    "Stock",
    "Supplier ID"
]

INVENTORY_HEADERS = [
    "Product ID",
    "Product Name",
    "Category",
    "Brand",
    "Stock",
    "Supplier ID"
]

SALES_HEADERS = [
    "Sale ID",
    "Product ID",
    "Customer Name",
    "Quantity",
    "Selling Price",
    "Total Amount",
    "Sale Date"
]


# -------------------- COMMON PDF FUNCTION --------------------

def create_pdf(filename, report_title, headers, data):

    pdf = SimpleDocTemplate(
        filename,
        pagesize=letter
    )

    styles = getSampleStyleSheet()

    elements = []

    # Project Title
    title = Paragraph(
        "<b><font size=18>CLOTHING INVENTORY MANAGEMENT SYSTEM</font></b>",
        styles["Title"]
    )

    elements.append(title)
    elements.append(Spacer(1, 12))

    # Report Title
    report = Paragraph(
        f"<b><font size=14>{report_title}</font></b>",
        styles["Heading2"]
    )

    elements.append(report)
    elements.append(Spacer(1, 10))

    # Date & Time
    current_date = datetime.now().strftime("%d-%m-%Y %I:%M %p")

    date = Paragraph(
        f"<b>Generated On :</b> {current_date}",
        styles["Normal"]
    )

    elements.append(date)
    elements.append(Spacer(1, 15))

    # Table Data
    table_data = [headers]

    for row in data:
        table_data.append(list(row))

    table = Table(table_data)

    table.setStyle(
        TableStyle([
            ('BACKGROUND', (0, 0), (-1, 0), colors.darkblue),
            ('TEXTCOLOR', (0, 0), (-1, 0), colors.whitesmoke),

            ('BACKGROUND', (0, 1), (-1, -1), colors.beige),

            ('GRID', (0, 0), (-1, -1), 1, colors.black),

            ('ALIGN', (0, 0), (-1, -1), 'CENTER'),

            ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),

            ('BOTTOMPADDING', (0, 0), (-1, 0), 10),

            ('TOPPADDING', (0, 1), (-1, -1), 8),

            ('FONTSIZE', (0, 0), (-1, -1), 10),
        ])
    )

    elements.append(table)
    elements.append(Spacer(1, 20))

    # Total Records
    total = Paragraph(
        f"<b>Total Records :</b> {len(data)}",
        styles["Heading3"]
    )

    elements.append(total)
    elements.append(Spacer(1, 15))

    # Footer
    footer = Paragraph(
        "<b>Generated by Clothing Inventory Management System</b>",
        styles["Normal"]
    )

    elements.append(footer)

    pdf.build(elements)

    print(f"\n{filename} Generated Successfully.")
    # -------------------- SUPPLIER REPORT --------------------

def supplier_report():

    conn = get_connection()
    cursor = conn.cursor()

    cursor.execute("""
        SELECT Supplier_ID,
               Supplier_Name,
               Contact_Person,
               Phone,
               Email,
               Address
        FROM Suppliers
        ORDER BY Supplier_ID
    """)

    suppliers = cursor.fetchall()

    if suppliers:

        print("\n========== SUPPLIER REPORT ==========\n")

        print(
            tabulate(
                suppliers,
                headers=SUPPLIER_HEADERS,
                tablefmt="grid"
            )
        )

        print("\nTotal Suppliers :", len(suppliers))

    else:

        print("No Supplier Records Found.")

    cursor.close()
    conn.close()
    # -------------------- SUPPLIER PDF --------------------

def generate_supplier_pdf():

    conn = get_connection()
    cursor = conn.cursor()

    cursor.execute("""
        SELECT Supplier_ID,
               Supplier_Name,
               Contact_Person,
               Phone,
               Email,
               Address
        FROM Suppliers
        ORDER BY Supplier_ID
    """)

    suppliers = cursor.fetchall()

    if suppliers:

        create_pdf(
            "Supplier_Report.pdf",
            "Supplier Report",
            SUPPLIER_HEADERS,
            suppliers
        )

    else:

        print("No Supplier Records Found.")

    cursor.close()
    conn.close()
    # -------------------- PRODUCT REPORT --------------------

def product_report():

    conn = get_connection()
    cursor = conn.cursor()

    cursor.execute("""
        SELECT Product_ID,
               Product_Name,
               Category,
               Brand,
               Selling_Price,
               Stock,
               Supplier_ID
        FROM Products
        ORDER BY Product_ID
    """)

    products = cursor.fetchall()

    if products:

        print("\n========== PRODUCT REPORT ==========\n")

        print(
            tabulate(
                products,
                headers=PRODUCT_HEADERS,
                tablefmt="grid"
            )
        )

        print("\nTotal Products :", len(products))

    else:

        print("No Product Records Found.")

    cursor.close()
    conn.close()
    # -------------------- PRODUCT PDF --------------------

def generate_product_pdf():

    conn = get_connection()
    cursor = conn.cursor()

    cursor.execute("""
        SELECT Product_ID,
               Product_Name,
               Category,
               Brand,
               Selling_Price,
               Stock,
               Supplier_ID
        FROM Products
        ORDER BY Product_ID
    """)

    products = cursor.fetchall()

    if products:

        create_pdf(
            "Product_Report.pdf",
            "Product Report",
            PRODUCT_HEADERS,
            products
        )

    else:

        print("No Product Records Found.")

    cursor.close()
    conn.close()
    # -------------------- INVENTORY REPORT --------------------

def inventory_report():

    conn = get_connection()
    cursor = conn.cursor()

    cursor.execute("""
        SELECT Product_ID,
               Product_Name,
               Category,
               Brand,
               Stock,
               Supplier_ID
        FROM Products
        ORDER BY Product_ID
    """)

    products = cursor.fetchall()

    if products:

        print("\n========== INVENTORY REPORT ==========\n")

        print(
            tabulate(
                products,
                headers=INVENTORY_HEADERS,
                tablefmt="grid"
            )
        )

        print("\nTotal Products :", len(products))

    else:

        print("No Inventory Records Found.")

    cursor.close()
    conn.close()
    # -------------------- INVENTORY PDF --------------------

def generate_inventory_pdf():

    conn = get_connection()
    cursor = conn.cursor()

    cursor.execute("""
        SELECT Product_ID,
               Product_Name,
               Category,
               Brand,
               Stock,
               Supplier_ID
        FROM Products
        ORDER BY Product_ID
    """)

    products = cursor.fetchall()

    if products:

        create_pdf(
            "Inventory_Report.pdf",
            "Inventory Report",
            INVENTORY_HEADERS,
            products
        )

    else:

        print("No Inventory Records Found.")

    cursor.close()
    conn.close()
    # -------------------- SALES REPORT --------------------

def sales_report():

    conn = get_connection()
    cursor = conn.cursor()

    cursor.execute("""
        SELECT Sale_ID,
               Product_ID,
               Customer_Name,
               Quantity,
               Selling_Price,
               Total_Amount,
               Sale_Date
        FROM Sales
        ORDER BY Sale_Date DESC
    """)

    sales = cursor.fetchall()

    if sales:

        print("\n========== SALES REPORT ==========\n")

        print(
            tabulate(
                sales,
                headers=SALES_HEADERS,
                tablefmt="grid"
            )
        )

        print("\nTotal Sales :", len(sales))

    else:

        print("No Sales Records Found.")

    cursor.close()
    conn.close()
    # -------------------- SALES PDF --------------------

def generate_sales_pdf():

    conn = get_connection()
    cursor = conn.cursor()

    cursor.execute("""
        SELECT Sale_ID,
               Product_ID,
               Customer_Name,
               Quantity,
               Selling_Price,
               Total_Amount,
               Sale_Date
        FROM Sales
        ORDER BY Sale_Date DESC
    """)

    sales = cursor.fetchall()

    if sales:

        create_pdf(
            "Sales_Report.pdf",
            "Sales Report",
            SALES_HEADERS,
            sales
        )

    else:

        print("No Sales Records Found.")

    cursor.close()
    conn.close()
    # -------------------- LOW STOCK REPORT --------------------

def low_stock_report():

    conn = get_connection()
    cursor = conn.cursor()

    low_stock_limit = 5

    cursor.execute("""
        SELECT Product_ID,
               Product_Name,
               Category,
               Brand,
               Stock,
               Supplier_ID
        FROM Products
        WHERE Stock < %s
        ORDER BY Stock ASC
    """, (low_stock_limit,))

    products = cursor.fetchall()

    if products:

        print("\n========== LOW STOCK REPORT ==========\n")

        print(
            tabulate(
                products,
                headers=INVENTORY_HEADERS,
                tablefmt="grid"
            )
        )

        print("\nTotal Low Stock Products :", len(products))

    else:

        print("\nAll Products Have Sufficient Stock.")

    cursor.close()
    conn.close()
    # -------------------- LOW STOCK PDF --------------------

def generate_low_stock_pdf():

    conn = get_connection()
    cursor = conn.cursor()

    low_stock_limit = 5

    cursor.execute("""
        SELECT Product_ID,
               Product_Name,
               Category,
               Brand,
               Stock,
               Supplier_ID
        FROM Products
        WHERE Stock < %s
        ORDER BY Stock ASC
    """, (low_stock_limit,))

    products = cursor.fetchall()

    if products:

        create_pdf(
            "Low_Stock_Report.pdf",
            "Low Stock Report",
            INVENTORY_HEADERS,
            products
        )

    else:

        print("No Low Stock Products Found.")

    cursor.close()
    conn.close()
    # -------------------- REPORTS MENU --------------------

def reports_menu():

    while True:

        print("\n========== REPORTS ==========")
        print("1. Supplier Report")
        print("2. Product Report")
        print("3. Inventory Report")
        print("4. Sales Report")
        print("5. Low Stock Report")
        print("6. Generate Supplier PDF")
        print("7. Generate Product PDF")
        print("8. Generate Inventory PDF")
        print("9. Generate Sales PDF")
        print("10. Generate Low Stock PDF")
        print("11. Back to Main Menu")

        choice = input("Enter Your Choice : ")

        if choice == "1":

            supplier_report()

        elif choice == "2":

            product_report()

        elif choice == "3":

            inventory_report()

        elif choice == "4":

            sales_report()

        elif choice == "5":

            low_stock_report()

        elif choice == "6":

            generate_supplier_pdf()

        elif choice == "7":

            generate_product_pdf()

        elif choice == "8":

            generate_inventory_pdf()

        elif choice == "9":

            generate_sales_pdf()

        elif choice == "10":

            generate_low_stock_pdf()

        elif choice == "11":

            print("Returning to Main Menu...")
            break

        else:

            print("Invalid Choice!")
